### ISSUE TITLE
Can't use it...

### ISSUE THREAD

**Issue by Spongyoshi** [DarkMatterCore/sbn64#1]
The .exe closes itself instantly so it can't be used to my knowledge...

**Comment by DarkMatterCore** [comment]
It's supposed to be used with the command shell (cmd). The program doesn't have a graphical user interface.

**Comment by Spongyoshi** [comment]
Oh, I see then... I thought it wouldn't change anything since it opened itself in a command shell anyway... So, it's not an issue, but I feel like this should be noted somewhere on the readme affiliated with it.
